### PR TITLE
Fix stale closures in React hooks

### PR DESCRIPTION
**Pull request by alesn**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This is a bugfix fixing stale closures in React hooks.

* **Other information**:
For consideration is to use eslint-plugin-react-hooks, which warns about the problems I fixed here.

### CODE REVIEW

**Review by antoniopresto — COMMENTED** [review]
Thanks for the feedback.  

The hook dependencies are missing on purpose, or we will fall into unnecessary processing (maybe infinite loops) as the configuration objects are not necessarily memorized, so they change with each render of the parent component.  The intent is that only the mask and value changing should trigger processing.  There are functions for comparing objects, but in that case for most uses it would be waste of processing. IMO many eslint rules are just personal opinions and sometimes pitfalls, specifically when using strict TS rules.

**Comment by antoniopresto** [comment]
Please, provide a reproduction example for the issue you found.

**Comment by alesn** [comment]
> The hook dependencies are missing on purpose, ...

That's bad. You can't do that. Then event handlers coming from outside of your package as props to antd-mask-input become stale as well and stop working correctly. Naturally you must prevent any possible infinite loops that your code could cause. In terms of possible speed optimization it is not worth it in an user input control even if it didn't break anything but it does break things because event handlers passed as props to antd-mask-input become stale.
I can confirm my fixed version I posted here resolves an issue in antd-mask-input

**Comment by antoniopresto** [comment]
Thanks to clarifying your problem, event handlers are not being updated, this is the bug. The issue can be solved changing onChange?.(ev) to props.onChange?.(ev) -
(not sure the line, Im on smartphone). I'm sure the code can better, but it is covering some edges maybe not visible at a first look.

**Comment by alesn** [comment]
Yes. (I understand you're on a phone ...) just don't forget also about the other event handlers that antd-mask-input takes as props, so those don't become stale either (onBlur, onPaste, onFocus, KEY_PRESS_EVENT). If you resolve the problem of stale event handlers another way, great!

**Comment by antoniopresto** [comment]
fixed by https://github.com/antoniopresto/antd-mask-input/commit/23b9808a3e06b0d877bf5957400410612f60d9cf

**Comment by antoniopresto** [comment]
Published at 2.0.6

**Comment by antoniopresto** [comment]
published as 2.0.6

**Comment by alesn** [comment]
I can't install 2.0.6 but the commit doesn't seem to address the staleness problem of the other event handlers I mentioned in my last comment above

**Comment by antoniopresto** [comment]
@alesn  I  had a problem with the build script, try 2.0.7

**Comment by antoniopresto** [comment]
Other event handlers are already using the prop reference or passed directly

**Comment by alesn** [comment]
I checked 2.0.7. 
It has the exact problems I warned you about in my last comment and you said were working correctly. Memoizing eventHandlers without dependencies on the individual props used within it makes those event handlers stale. 

antd-mask-input 2.0.7 is realistically at an early alpha version quality at best. I have reverted to version 0.1.15 and will not look at another 2.xx version again until a serious rewrite which includes all memoized functions having every single variable used within them listed in dependencies, unless the variable is a constant coming strictly from inside the package and doesn't use any variables from outside of it. There may be other synchronization problems of the internal state and what it should correctly be. At this stage there is no point looking for other bugs until this is done as of course it can't work correctly as it is now

**Comment by antoniopresto** [comment]
Dude, you know this is open source and I'm working for free right?  I don't even use antd anymore.  why don't you help me by providing a reproduction example as i asked?

**Comment by alesn** [comment]
I provided a PR, which fixes a number of the problems I mentioned. You rejected it saying those dependencies are not needed and that you will fix it another way. That didn't fix majority of them. Didn't even fix the individual stale handlers I specifically mentioned. At this state of the code there is no point in trying to set up a reproduction for a synchronization problem when based on the code it naturally it cannot work correctly

**Comment by antoniopresto** [comment]
I asked for a reproduction example because I know what I'm doing.  Maybe you're optimizing your memoized callbacks unnecessarily.  If you're unable to provide a use case so I can create the tests and examples in the storybook, clone this package and tweak it as you like. 

Everyone at some point in their lives has been an idiot just like you are right now, try better

**Comment by alesn** [comment]
> because I know what I'm doing

Clearly you don't know what you are doing as has been proven above. I tried to help you but where there is unjustified blind over-confidence, there is no help until a point of serious reflection comes.

**Comment by antoniopresto** [comment]
you are funny man. take a break hahaha

**Pull request closed without merging**
